# wajahat PIAIC80565

In [109]:
import numpy as np

In [110]:
IstArr=[1,2.0,"wajahat", True]

In [111]:
SecArr=[[1, 2, 3], [4, 5, 6],[7,8,9]]

1. np.array

In [112]:
ar = np.array(IstArr)
ar

array(['1', '2.0', 'wajahat', 'True'], dtype='<U32')

In [113]:
ar2=np.array(SecArr)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2.shape

In [114]:
ar.shape

(4,)

In [115]:
ar2.shape

(3, 3)

3.type

In [116]:
type(ar)

numpy.ndarray

In [117]:
type(ar2)

numpy.ndarray

4.ar.dtype

In [118]:
ar.dtype

dtype('<U32')

In [119]:
ar2.dtype

dtype('int32')

5. The element of array

In [120]:
ar[1]

'2.0'

In [121]:
ar2[2]

array([7, 8, 9])

6. slicing

In [122]:
ar2[1:,1]

array([5, 8])

In [123]:
ar2[:,1]

array([2, 5, 8])

7.flags

In [124]:
ar.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

7.strides

In [125]:
ar.strides

(128,)

In [126]:
ar2.strides

(12, 4)

8.dimensions

In [127]:
ar.ndim

1

In [128]:
ar2.ndim

2

9. data

In [129]:
ar.data

In [130]:
ar2.data

10.Size

In [131]:
ar2.size

9

In [132]:
ar.size

4

11. itemsize

In [133]:
ar.itemsize

128

In [134]:
ar2.itemsize

4

12.bytes

In [135]:
ar.nbytes

512

In [136]:
ar2.nbytes

36

13.base objects

In [137]:
ar2.base

14. transpose

In [138]:
ar.T

array(['1', '2.0', 'wajahat', 'True'], dtype='<U32')

In [139]:
ar2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

15. Real

In [140]:
ar.real

array(['1', '2.0', 'wajahat', 'True'], dtype='<U32')

In [141]:
ar2.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

16. image

In [142]:
ar.imag

array(['', '', '', ''], dtype='<U32')

In [143]:
ar2.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

17. flat

In [144]:
ar.flat

In [145]:
ar2.flat

18. ctypes

In [146]:
ar.ctypes

In [147]:
ar2.ctypes

19. item

In [148]:
ar.item(2)

'wajahat'

In [149]:
ar2.item(3)

4

20. list

In [150]:
lst=list(ar)

In [151]:
type(lst)

list

In [152]:
lst

['1', '2.0', 'wajahat', 'True']

21. itemset

In [153]:
ar2.itemset(1,2)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
ar2.itemset(2,4)

In [155]:
ar2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

22. tobytes

In [156]:
ar.tobytes()

b'1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x002\x00\x00\x00.\x00\x00\x000\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x

In [157]:
ar.tostring()

<ipython-input-157-a797511c4ebf>:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  ar.tostring()


b'1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x002\x00\x00\x00.\x00\x00\x000\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x

In [158]:
ar

array(['1', '2.0', 'wajahat', 'True'], dtype='<U32')

In [159]:
ar2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

23. astype

In [160]:
ar.astype(str)

array(['1', '2.0', 'wajahat', 'True'], dtype='<U32')

In [161]:
type(ar)

numpy.ndarray

24.byteswap

In [162]:
ar.byteswap

<function ndarray.byteswap>

In [163]:
ar

array(['1', '2.0', 'wajahat', 'True'], dtype='<U32')

25. Copy

In [164]:
ar2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [165]:
ar3=ar2.copy()

In [166]:
ar3

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
ar2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

26. fill

In [168]:
ar2.fill(0)

In [169]:
ar2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

27. view

In [170]:
ar.view()

array(['1', '2.0', 'wajahat', 'True'], dtype='<U32')

28. Reshape

In [171]:
ar2=([[0, 1],
       [2, 3],
       [4, 5]])

In [172]:
np.shape(ar2)

(3, 2)

In [173]:
np.reshape(ar3,(3,3))
ar3

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [174]:
np.shape(ar2)

(3, 2)

In [175]:
np.reshape(ar3,9)

array([1, 2, 4, 4, 5, 6, 7, 8, 9])

29. resize

In [176]:
ar4=np.array([[0, 1], [2, 3]], order='C')
ar4.resize((2, 1))

In [177]:
ar4

array([[0],
       [1]])

30. transpose

In [178]:
ar3

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [179]:
ar3.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [4, 6, 9]])

31. swapaxes

In [180]:
np.swapaxes(ar3,1,1)

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

32. flattern

In [181]:
ar3.flatten()

array([1, 2, 4, 4, 5, 6, 7, 8, 9])

33. ravel

In [182]:
ar3.ravel(order='F')

array([1, 4, 7, 2, 5, 8, 4, 6, 9])

34. squeez

In [183]:
ar3.squeeze()

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

35. sort

In [184]:
ar3=[[1,4], [3,1]]

In [185]:
a = np.array([[1,4], [3,1]])
a.sort(axis=1)
a

array([[1, 4],
       [1, 3]])

36. argsort

In [186]:
x = np.array([[0, 3], [2, 2]])
x

array([[0, 3],
       [2, 2]])

In [187]:
ind = np.argsort(x, axis=0)
ind

array([[0, 1],
       [1, 0]], dtype=int64)

37. nonezero

In [188]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
x

array([[3, 0, 0],
       [0, 4, 0],
       [5, 6, 0]])

In [189]:
np.nonzero(x)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

38. compress

In [190]:
np.compress([True,True],ar3)

array([1, 4])

In [191]:
ar3

[[1, 4], [3, 1]]

39.diagnal

In [192]:
ar4

array([[0],
       [1]])

In [193]:
ar4.diagonal()

array([0])

40.amax

In [194]:
ar2

[[0, 1], [2, 3], [4, 5]]

In [195]:
np.amax(ar2)

5

41. min

In [196]:
np.amin(ar2)

0

42. sum

In [197]:
np.sum(ar2)

15

43. mean

In [198]:
np.mean(ar2)

2.5

44.isdecimal()

In [199]:
np.isdecimal()

AttributeError: module 'numpy' has no attribute 'isdecimal'

45. count

In [202]:
a = np.array(['aljkh', '  wctsr  ', 'ers'])
a

array(['aljkh', '  wctsr  ', 'ers'], dtype='<U9')

In [203]:
np.char.count(a, 'b')

array([0, 0, 0])

In [204]:
np.char.count(a, 'B')

array([0, 0, 0])

In [205]:
np.char.count(a, 'a')

array([1, 0, 0])

46.endswith

In [206]:
np.char.endswith(a, 'a')

array([False, False, False])

47. find

In [207]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


48. searchsorted

In [208]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


49. filter

In [209]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


50. random

In [210]:
from numpy import random
x = random.randint(100)
print(x)

48


51. ufunc

In [211]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


DONE